'use strict';
// Modules
import navigation from './modules/navigation';
import dropdown from './modules/dropdown';
import sidebar from './modules/sidebar';
import popup from './modules/popup';
import videoBox from './modules/video-box';
import select from './modules/select';
import tabs from './modules/tabs';
import mobileFooter from './modules/mobile-footer';
import interTelInput from './modules/inter-tel-input';
import timetable from './modules/timetable';
import textAreaResize from './modules/textarea-resize';
import timeRecorderMapPreview from './modules/time-recorder-map-preview';
import timeRecorderMap from './modules/time-recorder-map';
import switchContent from './modules/switch-content';
import inputHighlight from './modules/input-highlight';
import inputAutoWidth from './modules/input-auto-width';
import calendarPopupOpen from './modules/calendar-popup-open';
import postImages from './modules/post-images';
import mediafiles from './modules/mediafiles';
import hideContent from './modules/hide-content';
import directory from './modules/directory';
import newMessage from './modules/new-message';
import usersNearbyMap from './modules/users-nearby-map';
import range from './modules/range';
import catalogSlider from './modules/catalog-slider';
import productDetailsSlider from './modules/product-details-slider';
import contentHeader from './modules/content-header';
import foodShopProduct from './modules/food-shop-product';
import scrollSpy from './modules/scroll-spy';
import contentScrollDesktop from './modules/content-scroll-desktop';
import contentScrollMobile from './modules/content-scroll-mobile';
import shopFinderMap from './modules/shop-finder-map';
import popupSwitcher from './modules/popup-switcher';
import checkboxToggleContent from './modules/checkbox-toggle-content';

// On document ready
$(function () {
  svg4everybody();
  scrollSpy();
  navigation();
  dropdown();
  sidebar();
  popup();
  videoBox();
  select();
  tabs();
  mobileFooter();
  interTelInput();
  timetable();
  textAreaResize();
  timeRecorderMapPreview();
  timeRecorderMap();
  hideContent();
  switchContent();
  inputHighlight();
  inputAutoWidth();
  calendarPopupOpen();
  postImages();
  mediafiles();
  directory();
  newMessage();
  usersNearbyMap();
  range();
  catalogSlider();
  productDetailsSlider();
  contentHeader();
  foodShopProduct();
  contentScrollDesktop();
  contentScrollMobile();
  shopFinderMap();
  popupSwitcher();
  checkboxToggleContent();
});

// On window load
$(window).on('load', function () { });
